import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MyImage from './my_image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Passover Mad Libs</title>
        <meta name="description" content="Generated by create next app and modified by the Modells" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Passover Mad Libs!
        </h1>
        <p>
          Select a story below to get started.
        </p>
        <ul>
          <li>
            <Link href="/long-hidden">
              The Long-Hidden Afikomen
            </Link>
          </li>
          <li>
            <Link href="/new-four-questions">
              A new Four Questions
            </Link>

          </li>
          <li>
            <Link href="/theSoupRecipe">
              The Soup Recipe
            </Link>

          </li>
          <li>
            <Link href="/storyOfPassover">
              Maverick's Story of Passover
            </Link>
          </li>

        </ul>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={22} />
          </span>
        </a>
      </footer>
    </div>
  )
}
